version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"  # OUTSIDE
      - "9093:9093"  # INSIDE
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"  # Отключите автоматическое создание тем
      KAFKA_REPLICATION_FACTOR: 1  # Установите фактор репликации на 1
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKER_CONNECT: "kafka:9093"  # Измените на kafka:9093
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka-net


  producer:
    container_name: producer
    build:
      context: ./producer
    depends_on:
      - kafka
    networks:
      - kafka-net

  consumer:
    container_name: consumer
    build:
      context: ./consumer
    depends_on:
      - kafka
    networks:
      - kafka-net

  consumer_api:
    container_name: consumer_api
    build:
      context: ./consumer_api
    depends_on:
      - kafka
    networks:
      - kafka-net
    ports:
      - "8000:8000"
    command: ["wait-for-it", "kafka:9093", "--timeout=30", "--", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]



networks:
  kafka-net:
    driver: bridge
